// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MouseEvent.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MouseEvent.proto</summary>
public static partial class MouseEventReflection {

  #region Descriptor
  /// <summary>File descriptor for MouseEvent.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MouseEventReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBNb3VzZUV2ZW50LnByb3RvIlgKCk1vdXNlRXZlbnQSDQoFZXZlbnQYASAB",
          "KAkSEgoKeF9wb3NpdGlvbhgCIAEoBRISCgp5X3Bvc2l0aW9uGAMgASgFEhMK",
          "C3RlbXBlcmF0dXJlGAQgASgFIkgKDlNldHRpbmdzVXBkYXRlEhEKBGNvZWYY",
          "ASABKAJIAIgBARIRCgRzaXplGAIgASgFSAGIAQFCBwoFX2NvZWZCBwoFX3Np",
          "emUiIgoORXhlY3V0ZVNjZW5hcm8SEAoIc2NlbmFyaW8YASABKAkifgoNQ2xp",
          "ZW50TWVzc2FnZRIcCgVtb3VzZRgBIAEoCzILLk1vdXNlRXZlbnRIABIjCghz",
          "ZXR0aW5ncxgCIAEoCzIPLlNldHRpbmdzVXBkYXRlSAASIwoIc2NlbmFyaW8Y",
          "AyABKAsyDy5FeGVjdXRlU2NlbmFyb0gAQgUKA21zZ2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MouseEvent), global::MouseEvent.Parser, new[]{ "Event", "XPosition", "YPosition", "Temperature" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SettingsUpdate), global::SettingsUpdate.Parser, new[]{ "Coef", "Size" }, new[]{ "Coef", "Size" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ExecuteScenaro), global::ExecuteScenaro.Parser, new[]{ "Scenario" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientMessage), global::ClientMessage.Parser, new[]{ "Mouse", "Settings", "Scenario" }, new[]{ "Msg" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class MouseEvent : pb::IMessage<MouseEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MouseEvent> _parser = new pb::MessageParser<MouseEvent>(() => new MouseEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MouseEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MouseEventReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MouseEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MouseEvent(MouseEvent other) : this() {
    event_ = other.event_;
    xPosition_ = other.xPosition_;
    yPosition_ = other.yPosition_;
    temperature_ = other.temperature_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MouseEvent Clone() {
    return new MouseEvent(this);
  }

  /// <summary>Field number for the "event" field.</summary>
  public const int EventFieldNumber = 1;
  private string event_ = "";
  /// <summary>
  ///down, up, block, unblock
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Event {
    get { return event_; }
    set {
      event_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "x_position" field.</summary>
  public const int XPositionFieldNumber = 2;
  private int xPosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int XPosition {
    get { return xPosition_; }
    set {
      xPosition_ = value;
    }
  }

  /// <summary>Field number for the "y_position" field.</summary>
  public const int YPositionFieldNumber = 3;
  private int yPosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int YPosition {
    get { return yPosition_; }
    set {
      yPosition_ = value;
    }
  }

  /// <summary>Field number for the "temperature" field.</summary>
  public const int TemperatureFieldNumber = 4;
  private int temperature_;
  /// <summary>
  /// 0-100
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Temperature {
    get { return temperature_; }
    set {
      temperature_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MouseEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MouseEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Event != other.Event) return false;
    if (XPosition != other.XPosition) return false;
    if (YPosition != other.YPosition) return false;
    if (Temperature != other.Temperature) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Event.Length != 0) hash ^= Event.GetHashCode();
    if (XPosition != 0) hash ^= XPosition.GetHashCode();
    if (YPosition != 0) hash ^= YPosition.GetHashCode();
    if (Temperature != 0) hash ^= Temperature.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Event.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Event);
    }
    if (XPosition != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(XPosition);
    }
    if (YPosition != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(YPosition);
    }
    if (Temperature != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Temperature);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Event.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Event);
    }
    if (XPosition != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(XPosition);
    }
    if (YPosition != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(YPosition);
    }
    if (Temperature != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Temperature);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Event.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Event);
    }
    if (XPosition != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(XPosition);
    }
    if (YPosition != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(YPosition);
    }
    if (Temperature != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Temperature);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MouseEvent other) {
    if (other == null) {
      return;
    }
    if (other.Event.Length != 0) {
      Event = other.Event;
    }
    if (other.XPosition != 0) {
      XPosition = other.XPosition;
    }
    if (other.YPosition != 0) {
      YPosition = other.YPosition;
    }
    if (other.Temperature != 0) {
      Temperature = other.Temperature;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Event = input.ReadString();
          break;
        }
        case 16: {
          XPosition = input.ReadInt32();
          break;
        }
        case 24: {
          YPosition = input.ReadInt32();
          break;
        }
        case 32: {
          Temperature = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Event = input.ReadString();
          break;
        }
        case 16: {
          XPosition = input.ReadInt32();
          break;
        }
        case 24: {
          YPosition = input.ReadInt32();
          break;
        }
        case 32: {
          Temperature = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class SettingsUpdate : pb::IMessage<SettingsUpdate>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SettingsUpdate> _parser = new pb::MessageParser<SettingsUpdate>(() => new SettingsUpdate());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SettingsUpdate> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MouseEventReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SettingsUpdate() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SettingsUpdate(SettingsUpdate other) : this() {
    _hasBits0 = other._hasBits0;
    coef_ = other.coef_;
    size_ = other.size_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SettingsUpdate Clone() {
    return new SettingsUpdate(this);
  }

  /// <summary>Field number for the "coef" field.</summary>
  public const int CoefFieldNumber = 1;
  private readonly static float CoefDefaultValue = 0F;

  private float coef_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Coef {
    get { if ((_hasBits0 & 1) != 0) { return coef_; } else { return CoefDefaultValue; } }
    set {
      _hasBits0 |= 1;
      coef_ = value;
    }
  }
  /// <summary>Gets whether the "coef" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCoef {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "coef" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCoef() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "size" field.</summary>
  public const int SizeFieldNumber = 2;
  private readonly static int SizeDefaultValue = 0;

  private int size_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Size {
    get { if ((_hasBits0 & 2) != 0) { return size_; } else { return SizeDefaultValue; } }
    set {
      _hasBits0 |= 2;
      size_ = value;
    }
  }
  /// <summary>Gets whether the "size" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSize {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "size" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSize() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SettingsUpdate);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SettingsUpdate other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Coef, other.Coef)) return false;
    if (Size != other.Size) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasCoef) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Coef);
    if (HasSize) hash ^= Size.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasCoef) {
      output.WriteRawTag(13);
      output.WriteFloat(Coef);
    }
    if (HasSize) {
      output.WriteRawTag(16);
      output.WriteInt32(Size);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasCoef) {
      output.WriteRawTag(13);
      output.WriteFloat(Coef);
    }
    if (HasSize) {
      output.WriteRawTag(16);
      output.WriteInt32(Size);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasCoef) {
      size += 1 + 4;
    }
    if (HasSize) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Size);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SettingsUpdate other) {
    if (other == null) {
      return;
    }
    if (other.HasCoef) {
      Coef = other.Coef;
    }
    if (other.HasSize) {
      Size = other.Size;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          Coef = input.ReadFloat();
          break;
        }
        case 16: {
          Size = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 13: {
          Coef = input.ReadFloat();
          break;
        }
        case 16: {
          Size = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ExecuteScenaro : pb::IMessage<ExecuteScenaro>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ExecuteScenaro> _parser = new pb::MessageParser<ExecuteScenaro>(() => new ExecuteScenaro());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ExecuteScenaro> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MouseEventReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ExecuteScenaro() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ExecuteScenaro(ExecuteScenaro other) : this() {
    scenario_ = other.scenario_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ExecuteScenaro Clone() {
    return new ExecuteScenaro(this);
  }

  /// <summary>Field number for the "scenario" field.</summary>
  public const int ScenarioFieldNumber = 1;
  private string scenario_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Scenario {
    get { return scenario_; }
    set {
      scenario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ExecuteScenaro);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ExecuteScenaro other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Scenario != other.Scenario) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Scenario.Length != 0) hash ^= Scenario.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Scenario.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Scenario);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Scenario.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Scenario);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Scenario.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Scenario);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ExecuteScenaro other) {
    if (other == null) {
      return;
    }
    if (other.Scenario.Length != 0) {
      Scenario = other.Scenario;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Scenario = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Scenario = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ClientMessage : pb::IMessage<ClientMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ClientMessage> _parser = new pb::MessageParser<ClientMessage>(() => new ClientMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ClientMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MouseEventReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientMessage(ClientMessage other) : this() {
    switch (other.MsgCase) {
      case MsgOneofCase.Mouse:
        Mouse = other.Mouse.Clone();
        break;
      case MsgOneofCase.Settings:
        Settings = other.Settings.Clone();
        break;
      case MsgOneofCase.Scenario:
        Scenario = other.Scenario.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientMessage Clone() {
    return new ClientMessage(this);
  }

  /// <summary>Field number for the "mouse" field.</summary>
  public const int MouseFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MouseEvent Mouse {
    get { return msgCase_ == MsgOneofCase.Mouse ? (global::MouseEvent) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Mouse;
    }
  }

  /// <summary>Field number for the "settings" field.</summary>
  public const int SettingsFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SettingsUpdate Settings {
    get { return msgCase_ == MsgOneofCase.Settings ? (global::SettingsUpdate) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Settings;
    }
  }

  /// <summary>Field number for the "scenario" field.</summary>
  public const int ScenarioFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ExecuteScenaro Scenario {
    get { return msgCase_ == MsgOneofCase.Scenario ? (global::ExecuteScenaro) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Scenario;
    }
  }

  private object msg_;
  /// <summary>Enum of possible cases for the "msg" oneof.</summary>
  public enum MsgOneofCase {
    None = 0,
    Mouse = 1,
    Settings = 2,
    Scenario = 3,
  }
  private MsgOneofCase msgCase_ = MsgOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MsgOneofCase MsgCase {
    get { return msgCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMsg() {
    msgCase_ = MsgOneofCase.None;
    msg_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ClientMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ClientMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Mouse, other.Mouse)) return false;
    if (!object.Equals(Settings, other.Settings)) return false;
    if (!object.Equals(Scenario, other.Scenario)) return false;
    if (MsgCase != other.MsgCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (msgCase_ == MsgOneofCase.Mouse) hash ^= Mouse.GetHashCode();
    if (msgCase_ == MsgOneofCase.Settings) hash ^= Settings.GetHashCode();
    if (msgCase_ == MsgOneofCase.Scenario) hash ^= Scenario.GetHashCode();
    hash ^= (int) msgCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (msgCase_ == MsgOneofCase.Mouse) {
      output.WriteRawTag(10);
      output.WriteMessage(Mouse);
    }
    if (msgCase_ == MsgOneofCase.Settings) {
      output.WriteRawTag(18);
      output.WriteMessage(Settings);
    }
    if (msgCase_ == MsgOneofCase.Scenario) {
      output.WriteRawTag(26);
      output.WriteMessage(Scenario);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (msgCase_ == MsgOneofCase.Mouse) {
      output.WriteRawTag(10);
      output.WriteMessage(Mouse);
    }
    if (msgCase_ == MsgOneofCase.Settings) {
      output.WriteRawTag(18);
      output.WriteMessage(Settings);
    }
    if (msgCase_ == MsgOneofCase.Scenario) {
      output.WriteRawTag(26);
      output.WriteMessage(Scenario);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (msgCase_ == MsgOneofCase.Mouse) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Mouse);
    }
    if (msgCase_ == MsgOneofCase.Settings) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Settings);
    }
    if (msgCase_ == MsgOneofCase.Scenario) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Scenario);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ClientMessage other) {
    if (other == null) {
      return;
    }
    switch (other.MsgCase) {
      case MsgOneofCase.Mouse:
        if (Mouse == null) {
          Mouse = new global::MouseEvent();
        }
        Mouse.MergeFrom(other.Mouse);
        break;
      case MsgOneofCase.Settings:
        if (Settings == null) {
          Settings = new global::SettingsUpdate();
        }
        Settings.MergeFrom(other.Settings);
        break;
      case MsgOneofCase.Scenario:
        if (Scenario == null) {
          Scenario = new global::ExecuteScenaro();
        }
        Scenario.MergeFrom(other.Scenario);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::MouseEvent subBuilder = new global::MouseEvent();
          if (msgCase_ == MsgOneofCase.Mouse) {
            subBuilder.MergeFrom(Mouse);
          }
          input.ReadMessage(subBuilder);
          Mouse = subBuilder;
          break;
        }
        case 18: {
          global::SettingsUpdate subBuilder = new global::SettingsUpdate();
          if (msgCase_ == MsgOneofCase.Settings) {
            subBuilder.MergeFrom(Settings);
          }
          input.ReadMessage(subBuilder);
          Settings = subBuilder;
          break;
        }
        case 26: {
          global::ExecuteScenaro subBuilder = new global::ExecuteScenaro();
          if (msgCase_ == MsgOneofCase.Scenario) {
            subBuilder.MergeFrom(Scenario);
          }
          input.ReadMessage(subBuilder);
          Scenario = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::MouseEvent subBuilder = new global::MouseEvent();
          if (msgCase_ == MsgOneofCase.Mouse) {
            subBuilder.MergeFrom(Mouse);
          }
          input.ReadMessage(subBuilder);
          Mouse = subBuilder;
          break;
        }
        case 18: {
          global::SettingsUpdate subBuilder = new global::SettingsUpdate();
          if (msgCase_ == MsgOneofCase.Settings) {
            subBuilder.MergeFrom(Settings);
          }
          input.ReadMessage(subBuilder);
          Settings = subBuilder;
          break;
        }
        case 26: {
          global::ExecuteScenaro subBuilder = new global::ExecuteScenaro();
          if (msgCase_ == MsgOneofCase.Scenario) {
            subBuilder.MergeFrom(Scenario);
          }
          input.ReadMessage(subBuilder);
          Scenario = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
